name: check build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  run_dune_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0

      - name: Checks
        run: |
          set -x
          eval $(opam env)

          # make sure we can run opam pin
          opam pin add fromager .

          # make sure opam package file is valid
          opam install opam-dune-lint
          opam lint
          opam-dune-lint

          # make sure the formatting is correct :)
          opam install ocamlformat.0.18.0
          fromager

